/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as BaseImport } from "./routes/_base"
import { Route as BaseIndexImport } from "./routes/_base/index"
import { Route as OnboardingInterestsImport } from "./routes/onboarding/interests"
import { Route as AuthSignupImport } from "./routes/auth/signup"
import { Route as AuthLoginImport } from "./routes/auth/login"
import { Route as AuthForgotPasswordImport } from "./routes/auth/forgot-password"
import { Route as AuthChangePasswordImport } from "./routes/auth/change-password"
import { Route as BaseSearchImport } from "./routes/_base/search"
import { Route as BaseSavedImport } from "./routes/_base/saved"
import { Route as BaseProfileImport } from "./routes/_base/profile"
import { Route as BaseDiscoverImport } from "./routes/_base/discover"
import { Route as BaseCategoryImport } from "./routes/_base/category"
import { Route as BaseArticleArticleIdImport } from "./routes/_base/article/$articleId"

// Create/Update Routes

const BaseRoute = BaseImport.update({
  id: "/_base",
  getParentRoute: () => rootRoute,
} as any)

const BaseIndexRoute = BaseIndexImport.update({
  path: "/",
  getParentRoute: () => BaseRoute,
} as any)

const OnboardingInterestsRoute = OnboardingInterestsImport.update({
  path: "/onboarding/interests",
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: "/auth/signup",
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: "/auth/login",
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  path: "/auth/forgot-password",
  getParentRoute: () => rootRoute,
} as any)

const AuthChangePasswordRoute = AuthChangePasswordImport.update({
  path: "/auth/change-password",
  getParentRoute: () => rootRoute,
} as any)

const BaseSearchRoute = BaseSearchImport.update({
  path: "/search",
  getParentRoute: () => BaseRoute,
} as any)

const BaseSavedRoute = BaseSavedImport.update({
  path: "/saved",
  getParentRoute: () => BaseRoute,
} as any)

const BaseProfileRoute = BaseProfileImport.update({
  path: "/profile",
  getParentRoute: () => BaseRoute,
} as any)

const BaseDiscoverRoute = BaseDiscoverImport.update({
  path: "/discover",
  getParentRoute: () => BaseRoute,
} as any)

const BaseCategoryRoute = BaseCategoryImport.update({
  path: "/category",
  getParentRoute: () => BaseRoute,
} as any)

const BaseArticleArticleIdRoute = BaseArticleArticleIdImport.update({
  path: "/article/$articleId",
  getParentRoute: () => BaseRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_base": {
      id: "/_base"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof BaseImport
      parentRoute: typeof rootRoute
    }
    "/_base/category": {
      id: "/_base/category"
      path: "/category"
      fullPath: "/category"
      preLoaderRoute: typeof BaseCategoryImport
      parentRoute: typeof BaseImport
    }
    "/_base/discover": {
      id: "/_base/discover"
      path: "/discover"
      fullPath: "/discover"
      preLoaderRoute: typeof BaseDiscoverImport
      parentRoute: typeof BaseImport
    }
    "/_base/profile": {
      id: "/_base/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof BaseProfileImport
      parentRoute: typeof BaseImport
    }
    "/_base/saved": {
      id: "/_base/saved"
      path: "/saved"
      fullPath: "/saved"
      preLoaderRoute: typeof BaseSavedImport
      parentRoute: typeof BaseImport
    }
    "/_base/search": {
      id: "/_base/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof BaseSearchImport
      parentRoute: typeof BaseImport
    }
    "/auth/change-password": {
      id: "/auth/change-password"
      path: "/auth/change-password"
      fullPath: "/auth/change-password"
      preLoaderRoute: typeof AuthChangePasswordImport
      parentRoute: typeof rootRoute
    }
    "/auth/forgot-password": {
      id: "/auth/forgot-password"
      path: "/auth/forgot-password"
      fullPath: "/auth/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/auth/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    "/auth/signup": {
      id: "/auth/signup"
      path: "/auth/signup"
      fullPath: "/auth/signup"
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    "/onboarding/interests": {
      id: "/onboarding/interests"
      path: "/onboarding/interests"
      fullPath: "/onboarding/interests"
      preLoaderRoute: typeof OnboardingInterestsImport
      parentRoute: typeof rootRoute
    }
    "/_base/": {
      id: "/_base/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof BaseIndexImport
      parentRoute: typeof BaseImport
    }
    "/_base/article/$articleId": {
      id: "/_base/article/$articleId"
      path: "/article/$articleId"
      fullPath: "/article/$articleId"
      preLoaderRoute: typeof BaseArticleArticleIdImport
      parentRoute: typeof BaseImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  BaseRoute: BaseRoute.addChildren({
    BaseCategoryRoute,
    BaseDiscoverRoute,
    BaseProfileRoute,
    BaseSavedRoute,
    BaseSearchRoute,
    BaseIndexRoute,
    BaseArticleArticleIdRoute,
  }),
  AuthChangePasswordRoute,
  AuthForgotPasswordRoute,
  AuthLoginRoute,
  AuthSignupRoute,
  OnboardingInterestsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_base",
        "/auth/change-password",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/signup",
        "/onboarding/interests"
      ]
    },
    "/_base": {
      "filePath": "_base.tsx",
      "children": [
        "/_base/category",
        "/_base/discover",
        "/_base/profile",
        "/_base/saved",
        "/_base/search",
        "/_base/",
        "/_base/article/$articleId"
      ]
    },
    "/_base/category": {
      "filePath": "_base/category.tsx",
      "parent": "/_base"
    },
    "/_base/discover": {
      "filePath": "_base/discover.tsx",
      "parent": "/_base"
    },
    "/_base/profile": {
      "filePath": "_base/profile.tsx",
      "parent": "/_base"
    },
    "/_base/saved": {
      "filePath": "_base/saved.tsx",
      "parent": "/_base"
    },
    "/_base/search": {
      "filePath": "_base/search.tsx",
      "parent": "/_base"
    },
    "/auth/change-password": {
      "filePath": "auth/change-password.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/onboarding/interests": {
      "filePath": "onboarding/interests.tsx"
    },
    "/_base/": {
      "filePath": "_base/index.tsx",
      "parent": "/_base"
    },
    "/_base/article/$articleId": {
      "filePath": "_base/article/$articleId.tsx",
      "parent": "/_base"
    }
  }
}
ROUTE_MANIFEST_END */
