/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as BaseRouteImport } from "./routes/_base"
import { Route as BaseIndexRouteImport } from "./routes/_base/index"
import { Route as OnboardingInterestsRouteImport } from "./routes/onboarding/interests"
import { Route as AuthSignupRouteImport } from "./routes/auth/signup"
import { Route as AuthLoginRouteImport } from "./routes/auth/login"
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password"
import { Route as AuthChangePasswordRouteImport } from "./routes/auth/change-password"
import { Route as BaseSearchRouteImport } from "./routes/_base/search"
import { Route as BaseSavedRouteImport } from "./routes/_base/saved"
import { Route as BaseProfileRouteImport } from "./routes/_base/profile"
import { Route as BaseDiscoverRouteImport } from "./routes/_base/discover"
import { Route as BaseCategoryRouteImport } from "./routes/_base/category"
import { Route as BaseArticleArticleIdRouteImport } from "./routes/_base/article/$articleId"

const BaseRoute = BaseRouteImport.update({
  id: "/_base",
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BaseRoute,
} as any)
const OnboardingInterestsRoute = OnboardingInterestsRouteImport.update({
  id: "/onboarding/interests",
  path: "/onboarding/interests",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/auth/signup",
  path: "/auth/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/auth/forgot-password",
  path: "/auth/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: "/auth/change-password",
  path: "/auth/change-password",
  getParentRoute: () => rootRouteImport,
} as any)
const BaseSearchRoute = BaseSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => BaseRoute,
} as any)
const BaseSavedRoute = BaseSavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => BaseRoute,
} as any)
const BaseProfileRoute = BaseProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => BaseRoute,
} as any)
const BaseDiscoverRoute = BaseDiscoverRouteImport.update({
  id: "/discover",
  path: "/discover",
  getParentRoute: () => BaseRoute,
} as any)
const BaseCategoryRoute = BaseCategoryRouteImport.update({
  id: "/category",
  path: "/category",
  getParentRoute: () => BaseRoute,
} as any)
const BaseArticleArticleIdRoute = BaseArticleArticleIdRouteImport.update({
  id: "/article/$articleId",
  path: "/article/$articleId",
  getParentRoute: () => BaseRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof BaseIndexRoute
  "/category": typeof BaseCategoryRoute
  "/discover": typeof BaseDiscoverRoute
  "/profile": typeof BaseProfileRoute
  "/saved": typeof BaseSavedRoute
  "/search": typeof BaseSearchRoute
  "/auth/change-password": typeof AuthChangePasswordRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/signup": typeof AuthSignupRoute
  "/onboarding/interests": typeof OnboardingInterestsRoute
  "/article/$articleId": typeof BaseArticleArticleIdRoute
}
export interface FileRoutesByTo {
  "/category": typeof BaseCategoryRoute
  "/discover": typeof BaseDiscoverRoute
  "/profile": typeof BaseProfileRoute
  "/saved": typeof BaseSavedRoute
  "/search": typeof BaseSearchRoute
  "/auth/change-password": typeof AuthChangePasswordRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/signup": typeof AuthSignupRoute
  "/onboarding/interests": typeof OnboardingInterestsRoute
  "/": typeof BaseIndexRoute
  "/article/$articleId": typeof BaseArticleArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_base": typeof BaseRouteWithChildren
  "/_base/category": typeof BaseCategoryRoute
  "/_base/discover": typeof BaseDiscoverRoute
  "/_base/profile": typeof BaseProfileRoute
  "/_base/saved": typeof BaseSavedRoute
  "/_base/search": typeof BaseSearchRoute
  "/auth/change-password": typeof AuthChangePasswordRoute
  "/auth/forgot-password": typeof AuthForgotPasswordRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/signup": typeof AuthSignupRoute
  "/onboarding/interests": typeof OnboardingInterestsRoute
  "/_base/": typeof BaseIndexRoute
  "/_base/article/$articleId": typeof BaseArticleArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/category"
    | "/discover"
    | "/profile"
    | "/saved"
    | "/search"
    | "/auth/change-password"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/signup"
    | "/onboarding/interests"
    | "/article/$articleId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/category"
    | "/discover"
    | "/profile"
    | "/saved"
    | "/search"
    | "/auth/change-password"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/signup"
    | "/onboarding/interests"
    | "/"
    | "/article/$articleId"
  id:
    | "__root__"
    | "/_base"
    | "/_base/category"
    | "/_base/discover"
    | "/_base/profile"
    | "/_base/saved"
    | "/_base/search"
    | "/auth/change-password"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/signup"
    | "/onboarding/interests"
    | "/_base/"
    | "/_base/article/$articleId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BaseRoute: typeof BaseRouteWithChildren
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OnboardingInterestsRoute: typeof OnboardingInterestsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_base": {
      id: "/_base"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_base/": {
      id: "/_base/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    "/onboarding/interests": {
      id: "/onboarding/interests"
      path: "/onboarding/interests"
      fullPath: "/onboarding/interests"
      preLoaderRoute: typeof OnboardingInterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/signup": {
      id: "/auth/signup"
      path: "/auth/signup"
      fullPath: "/auth/signup"
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/auth/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/forgot-password": {
      id: "/auth/forgot-password"
      path: "/auth/forgot-password"
      fullPath: "/auth/forgot-password"
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/change-password": {
      id: "/auth/change-password"
      path: "/auth/change-password"
      fullPath: "/auth/change-password"
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_base/search": {
      id: "/_base/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof BaseSearchRouteImport
      parentRoute: typeof BaseRoute
    }
    "/_base/saved": {
      id: "/_base/saved"
      path: "/saved"
      fullPath: "/saved"
      preLoaderRoute: typeof BaseSavedRouteImport
      parentRoute: typeof BaseRoute
    }
    "/_base/profile": {
      id: "/_base/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof BaseProfileRouteImport
      parentRoute: typeof BaseRoute
    }
    "/_base/discover": {
      id: "/_base/discover"
      path: "/discover"
      fullPath: "/discover"
      preLoaderRoute: typeof BaseDiscoverRouteImport
      parentRoute: typeof BaseRoute
    }
    "/_base/category": {
      id: "/_base/category"
      path: "/category"
      fullPath: "/category"
      preLoaderRoute: typeof BaseCategoryRouteImport
      parentRoute: typeof BaseRoute
    }
    "/_base/article/$articleId": {
      id: "/_base/article/$articleId"
      path: "/article/$articleId"
      fullPath: "/article/$articleId"
      preLoaderRoute: typeof BaseArticleArticleIdRouteImport
      parentRoute: typeof BaseRoute
    }
  }
}

interface BaseRouteChildren {
  BaseCategoryRoute: typeof BaseCategoryRoute
  BaseDiscoverRoute: typeof BaseDiscoverRoute
  BaseProfileRoute: typeof BaseProfileRoute
  BaseSavedRoute: typeof BaseSavedRoute
  BaseSearchRoute: typeof BaseSearchRoute
  BaseIndexRoute: typeof BaseIndexRoute
  BaseArticleArticleIdRoute: typeof BaseArticleArticleIdRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseCategoryRoute: BaseCategoryRoute,
  BaseDiscoverRoute: BaseDiscoverRoute,
  BaseProfileRoute: BaseProfileRoute,
  BaseSavedRoute: BaseSavedRoute,
  BaseSearchRoute: BaseSearchRoute,
  BaseIndexRoute: BaseIndexRoute,
  BaseArticleArticleIdRoute: BaseArticleArticleIdRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BaseRoute: BaseRouteWithChildren,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  OnboardingInterestsRoute: OnboardingInterestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
